Vagrant.require_version ">= 1.7.0"

Vagrant.configure(2) do |config|

  config.ssh.insert_key = false
  config.vm.box = "ubuntu/trusty64"
  config.vm.provider :virtualbox do |vb|
    vb.memory = 2048
    vb.cpus = 2
    vb.name = "solr"
  end

  config.vm.hostname = 'solr.dev'
  config.vm.network :private_network, ip: "192.168.60.15"

  config.vm.provision "ansible" do |ansible|
    ansible.verbose = "v"
    ansible.playbook = "vagrant.yml"
  end
end
